[tool.poetry]
name = "ci2024-finalproject"
version = "0.1.0"
description = ""
authors = ["FabioGigante <s328890@studenti.polito.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
